### ISSUE TITLE
[Bug] Mod does not work on lan worlds

### ISSUE THREAD

**Issue by SystemlessDev** [SuperMartijn642/Pottery#2]
**Version Info**
- Minecraft, 1.20.4
- Pottery 1.0.0

**What mod loader are you using?**: Forge

**Description of the Bug**
Pottery does not work with lan worlds. The client joining the world will be kicked with the NPE down below.

**Steps to Reproduce**
- Open two clients
- Create a world and open to lan
- Join said lan world with another client
- See that you've been kicked

**Log snippet**
```
[19:33:11] [Netty Server IO #3/ERROR] [minecraft/PacketEncoder]: Error receiving packet 115
java.lang.NullPointerException: Cannot invoke "net.minecraft.resources.ResourceLocation.toString()" because "p_130086_" is null
	at net.minecraft.network.FriendlyByteBuf.m_130085_(FriendlyByteBuf.java:642) ~[forge-1.20.4-49.0.14-client.jar:?] {re:classloading}
	at net.minecraft.network.protocol.game.ClientboundUpdateRecipesPacket.m_179469_(ClientboundUpdateRecipesPacket.java:52) ~[forge-1.20.4-49.0.14-client.jar:?] {re:classloading}
	at net.minecraft.network.FriendlyByteBuf.m_236828_(FriendlyByteBuf.java:208) ~[forge-1.20.4-49.0.14-client.jar:?] {re:classloading}
	at net.minecraft.network.protocol.game.ClientboundUpdateRecipesPacket.m_5779_(ClientboundUpdateRecipesPacket.java:28) ~[forge-1.20.4-49.0.14-client.jar:?] {re:classloading}
	at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:47) ~[forge-1.20.4-49.0.14-client.jar:?] {re:classloading}
	at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:15) ~[forge-1.20.4-49.0.14-client.jar:?] {re:classloading}
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final] {}
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final] {}
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final] {}
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final] {}
	at net.minecraft.network.Connection.m_243087_(Connection.java:297) ~[forge-1.20.4-49.0.14-client.jar:?] {re:classloading}
	at net.minecraft.network.Connection.m_292120_(Connection.java:290) ~[forge-1.20.4-49.0.14-client.jar:?] {re:classloading}
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar!/:4.1.97.Final] {}
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar!/:4.1.97.Final] {}
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar!/:4.1.97.Final] {}
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.97.Final.jar!/:4.1.97.Final] {}
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar!/:4.1.97.Final] {}
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar!/:4.1.97.Final] {}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}
```

**Comment by SuperMartijn642** [comment]
Should be fixed now in version 1.0.1.
Thank you for reporting the issue!
